version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: receitas
      POSTGRES_USER: rodrigo
      POSTGRES_PASSWORD: sua_senha
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: deploy/dockerfile
    env_file:
      - .env
    volumes:
      - ../static:/app/static
      - ../media:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/app/static
      - ../media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:

